.TH dyndnsup 1 LOCAL

.SH NAME

dyndnsup - Auto-update dynamic dns service

.SH SYNOPSIS

.B dyndnsup
.RB [ -v ]
|
.RB [ -h ]
|
.RB [ -c 
.IR file ]

.SH OPTIONS

.TP 9
.B -v
show version string
.TP 9
.B -h
show help information
.TP 4
.B -c
.IR file
specifies the config file to be used

.SH AVAILABILITY

Teorically all UNIX flavors. Tested in Linux and OpenBSD.

.SH AUTHOR

Jose V Beneyto, sepen@users.sourceforge.net
